### ISSUE TITLE
Movies in CYBERSTORM 2

### ISSUE THREAD

**Issue by Jeep-Eep** [juanitogan/rbxit#2]
Only get black screens, nothing.

**Comment by juanitogan** [comment]
What's the full path to your Storm folder?

I assume you mean all movies including the intro movie.

Info on your Windows version may also help if this is not a path issue.

**Comment by Jeep-Eep** [comment]
Win 10, Path: E:\CyberStorm 2\SIERRA\Storm. Full install.

**Comment by juanitogan** [comment]
I don't know if you read my install instructions here or not, but I caution there that you can't have a space in the path.  Thus, your "CyberStorm 2" folder needs to be changed to remove the space.  Windows 95 games shouldn't have this limitation, but it's still safest to follow old DOS rules for folder and file names with Win 95 games.

https://github.com/juanitogan/rbxit/wiki/CyberStorm-Series

**Comment by Jeep-Eep** [comment]
I've also noted that when I open the .avis in Windows Media Player, there's
audio, not video - VLC does it properly.

**Comment by Jeep-Eep** [comment]
Okay, reinstalling with the proper pathway fixed it -gahh, modern windows
had made me lazy.

**Comment by juanitogan** [comment]
Glad to hear you're good to go.

Yeah, Cinepak video doesn't always play in WMP even though the codec comes with every version of Windows thus far.  In some version of Windows (like 7?), you may have to go into Windows Features and turn on the legacy codecs (not in Win10).  In other installs, if I recall correctly, you have to tell WMP to recognize the legacy codecs somehow (and/or download them separately for some versions WMP).  I'm sure you can search the net for Cinepak and WMP if you really want to get that working.  Probably not worth the effort.  On my latest Win10 machines, WMP plays the avi's fine without any extra work, but I do so much random testing I can't say why at the moment.

**Comment by Jeep-Eep** [comment]
Just use VLC, it can do that natively for free.
