### ISSUE TITLE
3·D Ultra MiniGolf German patchers acting strange

### ISSUE THREAD

**Issue by joerg-nafcom** [juanitogan/rbxit#21]
Hi there, I do own what appears to be a German version of 3·D Ultra MiniGolf  AKA "MaxiMiniGolf" the "BigFun Software" edition.

I am running Windows 10 x64, Version 21H1, Build 19043.1052, I first tried downloading the 1.1. update from the sierrahelp site, but the update installer would report "file found not in old version", so I wonder whether this means the version on that CD is already the version 1.1 so I skipped that, 

Then I downloaded your patcher 3DUltraMiniGolf-German-10-11-Win7fix.r4.exe which would abort with "error during audio file patching, Maybe already patched, wrong region or unknown print", then I would download your patcher as perhaps what I have is the deluxe version without me knowing? 3DUltraMiniGolfDeluxe-German-20-Win7fix.r5.exe

It aborted with the same message. When trying the non-deluxe patcher once more and then the deluxe patcher again, the 2nd time aound the deluxe patcher would finally patch something but after some minutes also aborts with the error message error during audio file patching, Maybe already patched, wrong region or unknown print"

Well, it seems to have done something though as the game no longer appears to reandomly crash.

I wonder why the patcher for the deluxe version would first try abort and 2nd try do something and then finish with the same error message regardless?

**Comment by juanitogan** [comment]
Hi.  Yes, that is very weird.

If your game has 27 holes then you have the Deluxe.  18 is non-deluxe.  Yes, it looks like MaxiMiniGolf is the same as Deluxe.  I have a copy of the German disc from somewhere but I didn't know it was called (or, also called) MaxiMiniGolf because no files on the disc say that -- not the menus, nothing -- just the packaging says that, it appears.  I will update the wiki to include this new name (and, eventually, maybe, don't know when, the patcher).

It is possible there are two German versions of deluxe disc, but I doubt it.  (The French copy, for example, comes in two names but the same disc contents.)  All I can guess right now is that maybe if you start over from scratch with 3DUltraMiniGolfDeluxe-German-20-Win7fix.r5.exe (maybe you already did?) that it will work the first time (unless you have a scratched disc or some other disc error... or maybe my copy comes from a disc with an error).

Without seeing the errors, I cannot guess what happened.  But, if it didn't finish, then there is likely one or more RBX files that didn't get patched and may crash when you get to that hole.

**Comment by joerg-nafcom** [comment]
Hi there, thanks for your detailed and fast reply! 

I have dug a bit deeper, in contrast to your statement , it appears I have a 2.0 version of the game that is not mentioned anywhere neither on your site nor on the Sierra Help Pages.

Also in contrast to what you wrote, in my version not only the packaging says "MaxMiniGolf" but also inside the game. I will apply a screenshot.

It is hard for me to determine whether my version is Deluxe or not. It does have 18 holes option for new game, but also "neun deluxe" (which translates to "9 deluxe") perhaps this means the 27 deluxe version or not, no idea.

As I have tried many times and none of the patchers work properly, I assume that is because I have a version 2.0 that is mentioned and supported nowhere. I have wetransfered you my version after I sent off this reply, asking you to please look into it and adjust the patcher accordingly. I am a software tester for medical software for a living, so I am willing and hopefully help you to figure this out till it finally works with version 2.0 of the game release, too! :)

![image](https://user-images.githubusercontent.com/16625923/121667510-a7005500-caaa-11eb-9ef6-b4cef3d635c4.png)

Also you are right some courses still have the sound bug and crash like the drive-in cinema stage

**Comment by joerg-nafcom** [comment]
As I received a message that the wetransfer to your email address, could not be sent, I have sent you an invite on LinkedIN including the download link. hope you will read and accept and we can work together supporting this version too, thanks! :)

**Comment by joerg-nafcom** [comment]
doing a bit more of further digging here is what I found. Looked at your blog https://namethattech.wordpress.com/2016/01/18/fixing-up-old-computer-games/
which indicates that my version is what is listed at "3·D Ultra MiniGolf Deluxe v2.0, German"

here is the output of the patcher:


========================================================================
Patch for 3D Ultra MiniGolf Deluxe v2.0 (German)            -- release 5
========================================================================
This will patch the audio files in Minigolf Deluxe so that the game
will play on Windows 7 through 10 (and earlier, and maybe beyond).

This patch is for the Deluxe edition only.
The non-deluxe edition has its own patcher.

Drücken Sie eine beliebige Taste . . .

--- Patching files
--- Clearing read-only attribute if set on banshee.RBX
--- Trying German patch for banshee.RBX
xdelta3: source L:\MaxMiniGolf2.0\Minigolf\DATA\banshee.RBX source size 14.0 MiB [14661801] blksize 64.0 MiB window 64.0 MiB
xdelta3: 0: in 3.64 MiB: out 8.00 MiB: total in 3.64 MiB: out 8.00 MiB: 604 ms
xdelta3: 1: in 5.72 MiB: out 8.00 MiB: total in 9.37 MiB: out 16.0 MiB: 803 ms
xdelta3: 2: in 4.37 MiB: out 8.00 MiB: total in 13.7 MiB: out 24.0 MiB: 616 ms
xdelta3: 3: in 2.49 MiB: out 3.05 MiB: total in 16.2 MiB: out 27.1 MiB: 356 ms
xdelta3: finished in 2.4 sec; input 17017479 output 28369779 bytes (166.71%)
--- Clearing read-only attribute if set on bigshoe.RBX
--- Trying German patch for bigshoe.RBX
xdelta3: source L:\MaxMiniGolf2.0\Minigolf\DATA\bigshoe.RBX source size 8.51 MiB [8923291] blksize 64.0 MiB window 64.0 MiB
xdelta3: 0: in 5.25 MiB: out 8.00 MiB: total in 5.25 MiB: out 8.00 MiB: 806 ms
xdelta3: 1: in 2.18 MiB: out 7.75 MiB: total in 7.44 MiB: out 15.8 MiB: 348 ms
xdelta3: finished in 1.2 sec; input 7800384 output 16519636 bytes (211.78%)
--- Clearing read-only attribute if set on bugs.RBX
--- Trying German patch for bugs.RBX
xdelta3: source L:\MaxMiniGolf2.0\Minigolf\DATA\bugs.RBX source size 11.6 MiB [12123617] blksize 64.0 MiB window 64.0 MiB
xdelta3: 0: in 5.40 MiB: out 8.00 MiB: total in 5.40 MiB: out 8.00 MiB: 861 ms
xdelta3: 1: in 2.20 MiB: out 8.00 MiB: total in 7.60 MiB: out 16.0 MiB: 325 ms
xdelta3: 2: in 28.0 B: out 3.39 MiB: total in 7.60 MiB: out 19.4 MiB: 11 ms
xdelta3: finished in 1.2 sec; input 7972717 output 20335715 bytes (255.07%)
--- Clearing read-only attribute if set on cloud9.RBX
--- Trying German patch for cloud9.RBX
xdelta3: source L:\MaxMiniGolf2.0\Minigolf\DATA\cloud9.RBX source size 12.9 MiB [13478337] blksize 64.0 MiB window 64.0 MiB
xdelta3: 0: in 3.18 MiB: out 8.00 MiB: total in 3.18 MiB: out 8.00 MiB: 538 ms
xdelta3: 1: in 4.15 MiB: out 8.00 MiB: total in 7.33 MiB: out 16.0 MiB: 561 ms
xdelta3: 2: in 2.69 MiB: out 6.78 MiB: total in 10.0 MiB: out 22.8 MiB: 377 ms
xdelta3: finished in 1.5 sec; input 10508983 output 23885094 bytes (227.28%)
--- Clearing read-only attribute if set on deepsea.RBX
--- Trying German patch for deepsea.RBX
xdelta3: source L:\MaxMiniGolf2.0\Minigolf\DATA\deepsea.RBX source size 27.9 MiB [29268738] blksize 64.0 MiB window 64.0 MiB
xdelta3: 0: in 1.77 MiB: out 8.00 MiB: total in 1.77 MiB: out 8.00 MiB: 438 ms
xdelta3: 1: in 2.16 MiB: out 8.00 MiB: total in 3.93 MiB: out 16.0 MiB: 303 ms
xdelta3: 2: in 4.01 MiB: out 8.00 MiB: total in 7.94 MiB: out 24.0 MiB: 546 ms
xdelta3: 3: in 5.33 MiB: out 8.00 MiB: total in 13.3 MiB: out 32.0 MiB: 715 ms
xdelta3: 4: in 28.0 B: out 6.29 MiB: total in 13.3 MiB: out 38.3 MiB: 21 ms
xdelta3: finished in 2.0 sec; input 13909062 output 40156053 bytes (288.70%)
--- Clearing read-only attribute if set on dinosaur.RBX
--- Trying German patch for dinosaur.RBX
xdelta3: source L:\MaxMiniGolf2.0\Minigolf\DATA\dinosaur.RBX source size 20.1 MiB [21105715] blksize 64.0 MiB window 64.0 MiB
xdelta3: 0: in 5.08 MiB: out 8.00 MiB: total in 5.08 MiB: out 8.00 MiB: 825 ms
xdelta3: 1: in 1.65 MiB: out 8.00 MiB: total in 6.73 MiB: out 16.0 MiB: 242 ms
xdelta3: 2: in 28.0 B: out 8.00 MiB: total in 6.73 MiB: out 24.0 MiB: 27 ms
xdelta3: 3: in 28.0 B: out 2.92 MiB: total in 6.73 MiB: out 26.9 MiB: 10 ms
xdelta3: finished in 1.1 sec; input 7054750 output 28227955 bytes (400.13%)
--- Clearing read-only attribute if set on evenmore.RBX
--- Trying German patch for evenmore.RBX
xdelta3: source L:\MaxMiniGolf2.0\Minigolf\DATA\evenmore.RBX source size 13.0 MiB [13664828] blksize 64.0 MiB window 64.0 MiB
xdelta3: 0: in 2.23 MiB: out 8.00 MiB: total in 2.23 MiB: out 8.00 MiB: 410 ms
xdelta3: 1: in 4.73 MiB: out 8.00 MiB: total in 6.96 MiB: out 16.0 MiB: 633 ms
xdelta3: 2: in 5.39 MiB: out 6.65 MiB: total in 12.3 MiB: out 22.6 MiB: 717 ms
xdelta3: finished in 1.8 sec; input 12945127 output 23750324 bytes (183.47%)
--- Clearing read-only attribute if set on fairylnd.RBX
--- Trying German patch for fairylnd.RBX
xdelta3: source L:\MaxMiniGolf2.0\Minigolf\DATA\fairylnd.RBX source size 12.4 MiB [12961960] blksize 64.0 MiB window 64.0 MiB
xdelta3: 0: in 5.02 MiB: out 8.00 MiB: total in 5.02 MiB: out 8.00 MiB: 810 ms
xdelta3: 1: in 1.47 MiB: out 8.00 MiB: total in 6.49 MiB: out 16.0 MiB: 224 ms
xdelta3: 2: in 28.0 B: out 3.44 MiB: total in 6.49 MiB: out 19.4 MiB: 11 ms
xdelta3: finished in 1.0 sec; input 6802856 output 20388007 bytes (299.70%)
--- Clearing read-only attribute if set on fort.RBX
--- Trying German patch for fort.RBX
xdelta3: source L:\MaxMiniGolf2.0\Minigolf\DATA\fort.RBX source size 10.0 MiB [10493439] blksize 64.0 MiB window 64.0 MiB
xdelta3: 0: in 5.53 MiB: out 8.00 MiB: total in 5.53 MiB: out 8.00 MiB: 851 ms
xdelta3: 1: in 291 KiB: out 8.00 MiB: total in 5.82 MiB: out 16.0 MiB: 64 ms
xdelta3: 2: in 25.0 B: out 61.5 KiB: total in 5.82 MiB: out 16.1 MiB: 1 ms
xdelta3: finished in 918 ms; input 6101695 output 16840161 bytes (275.99%)
--- Clearing read-only attribute if set on future.RBX
--- Trying German patch for future.RBX
xdelta3: source L:\MaxMiniGolf2.0\Minigolf\DATA\future.RBX source size 35.4 MiB [37160319] blksize 64.0 MiB window 64.0 MiB
xdelta3: 0: in 4.35 MiB: out 8.00 MiB: total in 4.35 MiB: out 8.00 MiB: 783 ms
xdelta3: 1: in 957 KiB: out 8.00 MiB: total in 5.29 MiB: out 16.0 MiB: 147 ms
xdelta3: 2: in 1.42 MiB: out 8.00 MiB: total in 6.71 MiB: out 24.0 MiB: 207 ms
xdelta3: 3: in 1.19 MiB: out 8.00 MiB: total in 7.90 MiB: out 32.0 MiB: 178 ms
xdelta3: 4: in 1.30 MiB: out 8.00 MiB: total in 9.20 MiB: out 40.0 MiB: 195 ms
xdelta3: target window checksum mismatch: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!! Error during audio file patching                      !!!
!!! Maybe already patched, wrong region, or unknown print !!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Drücken Sie eine beliebige Taste . . .

You can see, that my version has a different future.RBX  than what the patcher expects, hence it results in a checksum error! The game disc has no read errors whatsoever, I have tried it 3 times, there was no read error ever, so the disk source is fine.

**Comment by juanitogan** [comment]
Ah, I see you are correct on all points.  Your German version is indeed different than the copy someone else gave me.  This is what mine looks like:

![image](https://user-images.githubusercontent.com/2923222/121791330-08591e80-cba6-11eb-8f93-13462dfbfb29.png)

So, yes, yours is deluxe (banshee, cloud9, and deepsea are some of the deluxe holes).  It looks like the publisher couldn't help tweaking a few of the holes as well as the menu.  Bugger.

Anyhow, I'll compare against your copy and get back.  Not sure when I'll find time to work up a new release... but maybe today or this weekend.

Thanks, again, for helping out.

**Comment by juanitogan** [comment]
Okay, future.rbx and Monster.rbx are reporting as different.  I suspect Big Fun Software found some branding in those two holes they wanted to change.  The AVI files are also different (and lame), but those don't need fixing.

After seeing this, I now suspect that someone, someday, will contact me with a French copy that I still need to support (the original Sierra version and not the Family Fun version).

I'll get back when the new patch is ready.

**Comment by joerg-nafcom** [comment]
Thanks for the quick update and further details. As "Monster.rbx" did not show up in the patcher for me, I assume this would be after future.rbx which I couldn't see as it aborted early.

Thanks, I will eagerly await your updated patch! :)

**Comment by juanitogan** [comment]
All done.  Release 6 is now published.  Let me know if you have any issues with it.

**Comment by joerg-nafcom** [comment]
Thanks, will try it tonight and get back to you! Project site (and perhaps blog too?) yet seems to miss for the deluxe German version “aka MaxiMiniGolf”)

**Comment by juanitogan** [comment]
Ah, yes, I forgot to update the readme here (but did update the other 3 places).  Thanks.

**Comment by joerg-nafcom** [comment]
tested it and works now, thanks a lot for the quick fix, really glad to see somebody taking his project serious! :) Glad to have yet another German version supported!

Cheers!
Joerg

**Comment by juanitogan** [comment]
Cheers!
