### ISSUE TITLE
3D Ultra Mini Golf (Family MegaHits version) seems to be incompatible

### ISSUE THREAD

**Issue by ks202005** [juanitogan/rbxit#22]
I ran the patch as directed, and the game certainly loads and plays without crashing, but the voice clips play over each other, and the MIDI music doesn't seem to be working (this version of the game doesn't have MP3s I'm pretty sure).

**Comment by juanitogan** [comment]
Can you tell me if this is the deluxe version or not?  From the box art, it looks like it isn't, but that's not a great indicator.  Also, yes, the non-deluxe has no MP3s.

Anyhow, what is the full path to your minigolf.exe file?  For example: C:\Games\Sierra\MINIGOLF\MINIGOLF.EXE

**Comment by ks202005** [comment]
I've never had Deluxe so I wasn't entirely sure, but there's no indication that it's the deluxe edition from the main menus, and [Zomb's Lair's article](https://www.zombs-lair.com/3d-ultra-minigolf-deluxe) on the Deluxe edition says there's 27 holes total, which there definitely isn't on my version - only 18. 

![image](https://user-images.githubusercontent.com/65844375/196285065-3e58337b-d959-4351-85c1-da47c457402a.png)
![image](https://user-images.githubusercontent.com/65844375/196285182-c995fc5d-b23f-45a8-84cf-a7be75536ae9.png)

For the game executable path, it's G:\Games\3D Ultra Mini Golf\MINIGOLF.EXE. I ran the patch inside the game install directory as the patch itself told me to do so.

**Comment by juanitogan** [comment]
Yes, you are correct this is not the deluxe version.  I'll add this info about the Family MegaHits print to the wiki.

Anyway, you missed this detail from the install wiki:

- ⚠️ Don't create a path with a space in it or else the MIDI music will not play (among other issues).
  - For example, this is my path: C:\Games\Sierra\MINIGOLF

Rename your "3D Ultra Mini Golf" folder to something without spaces and you'll find it fixes both the MIDI and the audio clips piling up.  As a general rule, it is best to stick to DOS standards for paths for Windows 95 games and earlier.  I believe you can use a folder name longer than 8 chars in this case but, when in doubt, shorten folder names as well.

**Comment by ks202005** [comment]
You're right, I did some how miss that direction! Unfortunately, however, I tried
- renaming it to have no spaces (G:\Games\3DUltraMiniGolf)
- renaming the folder name to under 8 characters (G:\Games\Golf)
- moving the folder to C:\ (C:\Games\Golf)

And both issues (no music and voice clips playing over each other, almost all at once) remain. Is it possible that this release is somehow slightly different in a way that would allow the patch to complete successfully, get the game mostly working, be installed correctly, but still have these issues? The CD also came with SimCity 2000, so I'm wondering if the release may have slight differences. 

EDIT: Making a fresh install by copying the \MINIGOLF\ folder from the CD to a new folder and running the patch again fixed all issues. Not sure why renaming the existing folder wouldn't fix it. 

Thank you very much for writing this patch!

**Comment by juanitogan** [comment]
Yeah, that is odd that a simple rename of the folder didn't work.  Best guess is that your first copy had something set in the INI file that was continuing to cause problems.  Like the music turned off.  It's been a long time since I troubleshot this, so I don't remember all the details, but I see my note under Outstanding Issues in the wiki that says turning off the music (and maybe v1.0 in general) can also cause these issues.

Anyway, glad you got it running.
