### ISSUE TITLE
Running patcher against german version fails

### ISSUE THREAD

**Issue by ghost** [juanitogan/rbxit#3]
Thank you so much for the 3-D Ultra Minigolf patcher, I just played my beloved childhood-game again after almost 18 years.
I am from Germany and my parentes liked that game a lot, too. I understand the english comments in the game, but my parents don't. So I headed up to ebayto buy a German version. 
I tried to patch the files, but it won't work, as they have other filesize than the English ones.
Is there a way to patch the German files in an easy way, too? I can send you the RBX-files, if that's a way )I would host them on dropbox).

Kind regards and thanks again for that patch.

**Comment by juanitogan** [comment]
Ahah!  So there is a German language version!  I was curious about that but unable to figure it out for sure.

Yes, put the RBX files up on Dropbox and post the link(s) to them here.  I should be able to work up a new patch shortly.  Hopefully, before Christmas.

Also note that one user has reported a bug in the xdelta3 patch program that only manifests on some computers.  So, hopefully, you won't be hit by that.  If you do, try another computer.  But wait for the new patch first before you worry about that.  You already said the file sizes are different, and I don't cover any RBX versions like that yet.

**Comment by ghost** [comment]
Yeah, it was very popular around ent of the '90s, especially the version with network-support. I think the popularity was given as it was part of some game collections which were released every year.

I uploaded the files to [Dropbox](https://www.dropbox.com/s/h6rqoxfcw6hi65k/MINIGOLF_german.rar?dl=0)

I'm using Win10 Pro x64. When I try to patch (version 1.0 or updated to 1.1) the following message appears:
```
xdelta3: source D:\MINIGOLF\DATA\BIGSHOE.RBX source size 8.64 MiB [9055257] blksize 64.0 MiB window 64.0 MiB
xdelta3: target window checksum mismatch: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent

!!! Failure, like, maybe, you already patched this copy, or wrong version !!!
```
After your reply I tested Win7 Pro x64, but the error is the same.

**Comment by juanitogan** [comment]
Thank you for providing a copy of all the files and for leaving it at v1.0.  It was very helpful to get all of it to handle both 1.0 and 1.1.  If I was more astute, I would have asked you to send all that.  You can take the rar down now if you like before others start leaching off it.

I have released a new version of the patch to include English and German for both 1.0 and 1.1.  Please give it a test and let me know if it works for you.  It's a rather large download now.

Here's the link for your convenience:
https://github.com/juanitogan/rbxit/releases/download/3dumg.patch.r3/3DUltraMiniGolf-10-11-Win7fix.r3.exe

Also note that you should not install to a path with spaces in it.  It not only prevents the music from playing but _anything_ that turns off the music also causes the hole's intro screen to not appear -- which then causes the both the intro audio and the first putter audio to play at the same time.  Messy.

**Comment by ghost** [comment]
Hello Juan,
the new patch works wonderful with german version as well the english version, with both versions 1.0 and 1.1. Thank you for your work. I really appreciate it.
Kind regards
Timo

**Comment by juanitogan** [comment]
Excellent!😁 Thank you for the test report and thank you for your willingness to help.  This game doesn't error very often on my current laptop so it was hard to make sure I got the fixes in right.  Ciao.
