### ISSUE TITLE
MiniGolf: Patch for French versions

### ISSUE THREAD

**Issue by cyril634** [juanitogan/rbxit#6]
Hi,

I'd like to propose patched RBX files for 3D Ultra MiniGolf (Deluxe and standard 1.0) concerning the French version.

https://files.cloud.orange.fr/cloudUpDown/V07.00.01/UpDownCloud/downloadFileAnonymous?fileId=__upload%2Frbx%2FMiniGolfDeluxe_french_rbxfix.zip&shareToken=GuTYPIYFH53ca21179d7

https://files.cloud.orange.fr/cloudUpDown/V07.00.01/UpDownCloud/downloadFileAnonymous?fileId=__upload%2Frbx%2FMiniGolf10_french_rbxfix.zip&shareToken=GuTYPIYFH53ca21179d7

I didn't find the French patch v1.1 for MiniGolf standard, so only v1.0 is patched.

Maybe you could add thoses files to your RBXIT Win7 Patches.

If you want to try, you can download ISO file for the French version:
3D Ultra Minigolf Deluxe: http://www.abandonware-france.org/telechargement/clic/http/37251/files/
3D Ultra Minigolf: http://www.abandonware-france.org/telechargement/clic/http/55785/files/

Hope it's useful!

Regards!

**Comment by juanitogan** [comment]
Wow.  I had no idea there was a French version so thank you! for all of this.  I'm pretty busy at the moment with two other projects so I can't say when I'll find time to look at this more and include it.  It could be a couple weeks or a couple months.

**Comment by maximilien-noal** [comment]
Hello,
I fix old games for the Abandonware-France website, and I've got the French version of Deluxe too, and I'm stuck. :)

Without the patch, the deluxe edition runs (sort of, all the voices play at the same time when playing), but only on Windows 10 so far. Not on Windows 7.

This corrected file for the French version of Deluxe should fix the game. Thank you both very much. :D

(also currently on Abandonware-France the non-Deluxe version uses Windows 3.11 inside DOSBox. It works but it's not perfect. So the patched file is interesting for this one too.)

**Comment by cyril634** [comment]
Nice to meet you Maximilien. I didn't know how to contact Abandonware-France to give you the patched RBX files. Take it.
You need to apply those "patch files" onto original RBX files.
I didn't provide already patched RBX files because they are too big. If you have any question, don't hesitate!
It works natively on Windows 10 x64.

**Comment by maximilien-noal** [comment]
Thank you. Indeed I have a question : what tool do I have to use to apply those binary patches ?
I have an hex editor but that's more for one-time instances.

P.S : To get in touch there is a "contact" link on the website, or else there is the forums at www.abandonware-forums.org - Feel free to stop by !

**Comment by cyril634** [comment]
You can use xdelta3.exe included in 
https://github.com/juanitogan/rbxit/releases/download/3dumgd.patch.r4/3DUltraMiniGolfDeluxe-20-Win7fix.r4.exe
Have a look to setup.bat, you can use the following command line
`xdelta3 -dfv -s banshee.rbx banshee_f.patch banshee.WIN7FIX`
to apply patch
(you can delete *.WIN7FIX files if everything is ok)

**Comment by maximilien-noal** [comment]
Ah, I had a feeling it was xdelta but didn't find it already compiled. Thanks !

**Comment by juanitogan** [comment]
Hi everybody.  It sounds like I need to work up the French patch soon.  I will start work on that now.  It takes only a few minutes to build the patches (which Cyril already did) but it can take a few hours to get through all the testing I do.  Also, considering I now have 5 non-deluxe versions and 4 deluxe versions to support, changes take longer and longer to test.  But, considering the English and German patch is already too big, I plan to start splitting them up to separate patches.  So, here's my new plan:

I will publish the French patches as soon as possible and then think about whether or not to split up the English and German patch.  This should get you a patch today or tomorrow.

Until then... keep talking 😃 and thank you for helping each other.

**Comment by maximilien-noal** [comment]
Sounds great ! I will integrate it asap in a full game installer, and test the patch too on my end once it's available.
This automated setup will then eventually appear on the website and will include thanks to both of you and a link to the rbxit homepage. :)

**Comment by juanitogan** [comment]
Thank you, Maximilien.  If building custom installers, you might consider just zipping up a patched game folder and distributing that.  I considered going that route myself but chose to just focus on patching and avoiding any possible copyright problems.  I also have other issues noted in my wiki which may or may not be addressable in a custom installer (such as the legacy networking files in Win 10).

I will likely also link your ISOs in the wiki.

**Comment by juanitogan** [comment]
BTW, my internet searches tell me that there is a French 1.1 upgrade out there... somewhere.  There is a reference to \sierra\MGPAT11F.EXE on a French Canadian's website: http://pages.videotron.com/markim/htms/CD-125-999.TXT

**Comment by cyril634** [comment]
I tried to contact this guy 2 weeks ago... no answer

**Comment by maximilien-noal** [comment]
Here is the full automated installer for the French release of Minigolf Deluxe. It is on my Google Drive for now :
https://drive.google.com/open?id=0ByGL9C4M9ZvXcG9hUmk2em9BczQ
It seems to work well. Or at least, it didn't crash on Windows 7 and the voices weren't all playing at the same time. Very nice !

It contains a zipped full installation folder, so you can get the fully patched RBX files that way.

**Comment by maximilien-noal** [comment]
Coninuing my limited testing : Some sounds produce only static noise with a high volume compared to the rest.
And I just had a crash afterwards (but not instantly after).
I guess it still fights back. :)
I will wait for the proper patch and update the installer once it's available.

**Comment by juanitogan** [comment]
The French patches are uploaded and on the wiki now.  Let me know if they give any issues.

Please note, as the wiki also warns, that it is best to stick to old DOS rules of folder names with Windows 95 games.  With non-deluxe MG, a space leads to no music, which leads to SFX piling up.  With deluxe (and I just found this), a long folder name (>23 chars) leads to black screens.

**Comment by maximilien-noal** [comment]
Minigolf Deluxe French patch integrated into the updated setup above.

It works very well :
- No crashes
- No high-pitched static noises
- MIDI music working

Thank you !

One tiny issue :
- The first time a level is presented (not when you retry the level), several voice lines are playing at once, making it difficult to figure out what they are saying.

**Comment by juanitogan** [comment]
Thank you for the report.  It helps to hear the issue about the voices playing over each other in the deluxe version.  That is a common problem in v1.x but not in the deluxe version.  I did run into it once during testing (I believe) but I couldn't find a fix for it and it went away after testing another version and/or after hibernate.  I haven't been able to reproduce it since and I can't find a fix for it without reproducing it.  I might need to test on an older machine because this one doesn't even always crash on the audio, even without the patches (although hibernating and waking up again often lets the game crash again without a patch, which makes little sense).

Keep me posted on the issue -- if it goes away or not, etc.

**Comment by sebsebseb1982** [comment]
Hi ! This issue is a bit old but would you still be intersted if I can find it ? I'm pretty sure I have this french patch somewhere

**Comment by juanitogan** [comment]
Of course!  No issue is too old (or too closed) for fixing up old games.
