### ISSUE TITLE
Wont Install

### ISSUE THREAD

**Issue by NevoraskiA** [juanitogan/rbxit#7]
Have the non-deluxe version of 3-D Ultra Minigolf from 1997 on a Family MegaHits cd... I'm running Windows 10 64 bit (computer has both 32/64 bit c:/programfiles folders)

I click autorun and the installer opens up... where it says install, uninstall, run, and quit.

Run and Uninstall don't let me click on them. If I click on quit it closes the installer. If I click install it says "The program or feature "blah blah blah" cannot start or run due to incompatibility with 64-bit versions of Windows. Please contact the software vendor to ask if a 64-bit Windows compatible version is available.

I did try copying the files off the cd... and downloading and running the patcher, but the patcher fails... I can't even install the game in the first place (which you did have it installed in your youtube video... it just wouldn't run)

I have tried both compatibility mode and running as administrator and neither has worked... as I'm stuck with all 64-bit options.

**Comment by juanitogan** [comment]
Sorry to hear you're having trouble.

Many install programs from this era are 16-bit or a combo of 32-bit and 16-bit programs.  Thus, they don't run on Windows later than XP, basically.  I didn't "install" it for the YouTube video but copied the Minigolf folder as described in my install wiki.  If you can't run it (meaning it at least opens the background screen before it gives an error) by doing that alone then you have other problems to solve first.  The Family Megahits copy is not yet known to have any unusual issues here.

If you have problems with the patcher after knowing you have a clean and partly working copy from your disc, then please post the contents of the DOS patcher window here so I can see what's going on.

Best of luck.

**Comment by juanitogan** [comment]
Closed due to inactivity.
